name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Configure Gradle for CI
      run: |
        echo "org.gradle.daemon=false" >> gradle.properties
        echo "org.gradle.parallel=true" >> gradle.properties
        echo "org.gradle.caching=true" >> gradle.properties
        echo "org.gradle.configureondemand=true" >> gradle.properties

    - name: Pre-download dependencies
      run: |
        ./gradlew dependencies --no-daemon --no-build-cache || true
        ./gradlew --stop

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run Lint
      run: ./gradlew lintDebug --no-daemon --no-build-cache
      
    - name: Build with Gradle
      run: ./gradlew build --no-daemon --no-build-cache
